# Generated by Django 3.2 on 2021-04-22 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=uuid.UUID('b0558e7b-a34b-11eb-b391-8c554a970c06'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=uuid.UUID('b0558e7c-a34b-11eb-8dac-8c554a970c06'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CustAuthToken',
            fields=[
                ('token_id', models.CharField(default=uuid.UUID('b0558e7d-a34b-11eb-af15-8c554a970c06'), max_length=50, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_service.account')),
            ],
        ),
    ]
