# Generated by Django 3.2 on 2021-04-22 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0002_auto_20210422_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=uuid.UUID('323c30e7-a34d-11eb-8e79-8c554a970c06'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='custauthtoken',
            name='token_id',
            field=models.CharField(default=uuid.UUID('323c30e9-a34d-11eb-8613-8c554a970c06'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=uuid.UUID('323c30e8-a34d-11eb-97ed-8c554a970c06'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(null=True),
        ),
    ]
